### ISSUE TITLE
What modules to include

### ISSUE THREAD

**Issue by Katrix** [illyohs/Scorg#2]
As time goes on, the scala library is getting more and more modularized. Which of these modules will be included in Scorg, and which will users have to download themselves? Currently you have scala library, parser combinators, java 8 compat, and reflection. Why specifically these? 

Also, what is the update policy for the other libraries. Is updating okay if the change is backwards compatible?

If you look at the work being done on the scala platform, should anything there be considered?

**Comment by 0xilly** [comment]
The reason for the current modules are simply included because they are provided by Forge. I want to keep them the stable as possible but if there is backwards compatible change and a recommended build ill be willing to update otherwise we'll do what Forge does and wait for a major MC update. As for the platform being modularised we'll deal with it when it happens. If it's a breaking change we might have to wait for a major MC release to prevent mods from breaking or if everyone lobbies me to update I'll just update.

_Sent from my Samsung SM-G930P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Katrix** [comment]
If the aim is to provide what forge currently provides, you're missing stuff like the Scala compiler, scala swing, scala xml, and so on. Personally I don't think those should be in this as they are so rarely used, and don't have too much of a use case. Personally I'm a bit unsure if even the parser combinators should be included. Their performance is terrible, and there is much better options. Reflect is probably fine to let it stay, even though it's experimental and bad practice in scala.

**Comment by 0xilly** [comment]
There was a discussion of what to include in IRC and it was decided to drop swing XML and the compiler

_Sent from my Samsung SM-G930P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by 0xilly** [comment]
These rules aren't set in stone if there's enough movement towards one or the other I'll add or remove the dependency

_Sent from my Samsung SM-G930P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
